### PR TITLE
Use https to clone build system repos

### PR DESCRIPTION
**Pull request by metalefty**
While here, remove duplicate entry for alma-tests-cacher.

Resolves: https://github.com/AlmaLinux/build-system/issues/182

### CODE REVIEW

**Review by zklevsha — COMMENTED** [review]
I not sure that we should switch to https to be honest
Dev deploy is created mainly for development env, and contributing with ssh remote  is more convinient because we can push without password authentication

Maybe we can add addtional variable `clone_with_ssh = true/false` and based on that variable generate correct remote urls?

**Comment by metalefty** [comment]
I use HTTPS to clone and I add SSH URL to push in my environment.

```
% git remote -v
origin  https://github.com/AlmaLinux/albs-web-server.git (fetch)
origin  git@github.com:AlmaLinux/albs-web-server.git (push)
```

One of the reasons why I made this pull request is [you added HTTPS URL recently](https://github.com/AlmaLinux/albs-deploy/pull/8/commits/f7c15d242246065342c17cc6056b9dd52a3f3cf5).  I thought you prefer HTTPS rather than SSH.

**Comment by zklevsha** [comment]
I dont have strong opinion on https vs ssh, but maybe yours example will be the best solution i.e.
fetch with https and push ssh: 
```
origin  https://github.com/AlmaLinux/albs-web-server.git (fetch)
origin  git@github.com:AlmaLinux/albs-web-server.git (push)
```

I did not found how we can update remote with ansible `git` module, but we always can use `command` module for updating origin

**Comment by codyro** [comment]
> I did not found how we can update remote with ansible git module, but we always can use command module for updating origin

I'm not sure if this will work, but with the [git_config](https://docs.ansible.com/ansible/2.9/modules/git_config_module.html) module you may be able to do something like this:

(untested) 
```yaml
- name: Update git repository
  hosts: all
  tasks:
    - name: Update repository fetch url
      community.general.git_config:
        repo: ./somerepo
        name: remote.origin.url
        value: https://github.com/codyro/somerepo.git
        scope: local

    - name: Update repository push url
      community.general.git_config:
        repo: ./somerepo
        name: remote.origin.pushurl
        value: git@github.com:codyro/somerepo.git
        scope: local
```

**Comment by metalefty** [comment]
Added a task to set pushurl as @codyro mentioned. I confirmed it works for me.

**Review by zklevsha — APPROVED** [review]

**Pull request merged**
