### PR TITLE
Add alma-tests-cacher

### PR DESCRIPTION
**Pull request by metalefty**
Resolves: https://github.com/AlmaLinux/build-system/issues/132#issuecomment-1898357643

### CODE REVIEW

**Comment by javihernandez** [comment]
@metalefty, can you update with current master? Commit checker should not complain after https://github.com/AlmaLinux/albs-deploy/commit/52bc16de0b4480100bd1168372e74b61be27b395

**Comment by metalefty** [comment]
Force-pushed!

**Review by javihernandez — APPROVED** [review]

**Comment by javihernandez** [comment]
> Force-pushed!

Thanks, CI is happy now! :smile:

**Comment by zklevsha** [comment]
Issue was fixed today by merging https://github.com/AlmaLinux/albs-deploy/pull/8

**Review by Korulag — APPROVED** [review]

**Comment by metalefty** [comment]
Oops, now the yaml file duplicate alma-tests-cacher definitions.
```
albs_repos:
  albs-frontend: git@github.com:AlmaLinux/albs-frontend.git
  albs-node: git@github.com:AlmaLinux/albs-node.git
  albs-web-server: git@github.com:AlmaLinux/albs-web-server.git
  albs-sign-node: git@github.com:AlmaLinux/albs-sign-node.git
  alma-tests-cacher: git@github.com:AlmaLinux/alma-tests-cacher.git
  repo-beholder: git@github.com:AlmaLinux/repo-beholder.git
  alts: git@github.com:AlmaLinux/alts.git
  albs-sign-file: git@github.com:AlmaLinux/albs-sign-file.git
  alma-tests-cacher: https://github.com/AlmaLinux/alma-tests-cacher
```

**Pull request merged**
